apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: external-secrets
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: default
    source:
        path: deploy/us-east-02-internal/components/external-secrets
        repoURL: https://github.com/brenix/holos-demo.git
        targetRevision: main
