apiVersion: v1
data:
  ClusterValues: |
    {}
  ScopeValues: |
    policies:
      mutateLBTrafficPolicy: false
  StageValues: |
    replicas: 1
    dopplerConfig: dev
kind: ConfigMap
metadata:
  labels:
    example.com/cluster.name: dev1a-internal
    example.com/cluster.scope: internal
    example.com/cluster.stage: dev
  name: cluster-specific-values
