apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: podinfo
    namespace: argocd
spec:
    destination:
        server: https://kubernetes.default.svc
    project: default
    source:
        path: deploy/clusters/us-west-01a-customer/projects/setup/components/podinfo
        repoURL: https://github.com/brenix/holos-demo.git
        targetRevision: main
