apiVersion: v1
data:
  ClusterValues: |
    networkAllocations:
      podCIDRs:
        - 172.26.32.0/20
      serviceCIDRs:
        - 172.26.68.0/23
  ScopeValues: |
    policies:
      mutateLBTrafficPolicy: true
  StageValues: |
    replicas: 3
    dopplerConfig: prod
kind: ConfigMap
metadata:
  labels:
    example.com/cluster.name: us-west-01a-customer
    example.com/cluster.scope: customer
    example.com/cluster.stage: prod
  name: cluster-specific-values
