apiVersion: v1
data:
  ClusterValues: |
    {}
  ScopeValues: |
    policies:
      mutateLBTrafficPolicy: true
  StageValues: |
    replicas: 3
    dopplerConfig: prod
kind: ConfigMap
metadata:
  labels:
    example.com/cluster.name: us-east-02a-customer3
    example.com/cluster.scope: customer
    example.com/cluster.stage: prod
  name: cluster-specific-values
