apiVersion: v1
data:
  values: |
    replicas: 1
    dopplerConfig: dev
kind: ConfigMap
metadata:
  labels:
    example.com/cluster.scope: internal
    example.com/cluster.stage: dev
  name: values-by-cluster-stage
