apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: node-local-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-local-dns
    app.kubernetes.io/version: 1.23.0
    helm.sh/chart: node-local-dns-2.1.0
  name: node-local-dns
  namespace: kube-system
---
apiVersion: v1
data:
  Corefile: |-
    .:53 {
      errors
      cache 30 {
      }
      reload
      log . combined {
        class all
      }
      loop
      bind 169.254.20.11
      forward . __PILLAR__UPSTREAM__SERVERS__ {
      }
      prometheus :9253
      health 169.254.20.11:8080
    }
    in-addr.arpa:53 {
      errors
      cache 30 {
      }
      reload
      log . combined {
        class all
      }
      loop
      bind 169.254.20.11
      forward . __PILLAR__UPSTREAM__SERVERS__ {
      }
      prometheus :9253
      health 169.254.20.11:8080
    }
    ip6.arpa:53 {
      errors
      cache 30 {
      }
      reload
      log . combined {
        class all
      }
      loop
      bind 169.254.20.11
      forward . __PILLAR__UPSTREAM__SERVERS__ {
      }
      prometheus :9253
      health 169.254.20.11:8080
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: node-local-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-local-dns
    app.kubernetes.io/version: 1.23.0
    helm.sh/chart: node-local-dns-2.1.0
  name: node-local-dns
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: node-local-dns
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-local-dns
    app.kubernetes.io/version: 1.23.0
    helm.sh/chart: node-local-dns-2.1.0
  name: node-local-dns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-local-dns
      app.kubernetes.io/name: node-local-dns
  template:
    metadata:
      annotations:
        checksum/configmaps: 82cf58c47d79ab9208fcb1aeab60188ae82275fc801e97b0a10e81a2f440d8d8
        prometheus.io/port: "9253"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: node-local-dns
        app.kubernetes.io/name: node-local-dns
    spec:
      affinity: {}
      containers:
      - args:
        - -localip
        - 169.254.20.11
        - -skipteardown=true
        - -setupinterface=true
        - -setupiptables=false
        - -health-port
        - "8080"
        - -upstreamsvc
        - kube-dns
        - -conf
        - /etc/Corefile
        - -syncinterval
        - 1ns
        - -interfacename
        - nodelocaldns
        - -metrics-listen-address
        - 0.0.0.0:9353
        image: registry.k8s.io/dns/k8s-dns-node-cache:1.23.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            host: 169.254.20.11
            path: /health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        name: node-local-dns
        ports:
        - containerPort: 9253
          name: metrics
          protocol: TCP
        readinessProbe: null
        resources:
          requests:
            cpu: 30m
            memory: 50Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - mountPath: /etc/coredns
          name: config
      dnsPolicy: Default
      hostNetwork: true
      imagePullSecrets: []
      nodeSelector: {}
      priorityClassName: system-node-critical
      securityContext: {}
      serviceAccountName: node-local-dns
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - configMap:
          items:
          - key: Corefile
            path: Corefile.base
          name: node-local-dns
        name: config
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
